<?php



/**
 * Skeleton subclass for representing a row from the 'file_status' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Thu May 11 06:22:35 2017
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class FileStatus extends BaseFileStatus
{
}
