# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
top:
  url:   /
  param: { module: top, action: index }

entry:
  url:  /entry
  param: { module: user, action: entryInput }

entry_conf:
  url:  /entry/confirm
  param: { module: user, action: entryConf }

entry_comp:
  url:  /entry/complete/:provisional_key
  param: { module: user, action: entryComp }

entry_success:
  url:  /entry/success
  param: { module: user, action: entrySuccess }

login:
  url:  /login
  param: { module: auth, action: login }

logout:
  url:  /logout
  param: { module: auth, action: logout }

user_top:
  url:  /user
  param: { module: user, action: index }

contents:
  url:  /contents
  param: { module: contents, action: index }

project_top:
  url:  /project
  param: { module: project, action: index }

project_detail:
  url:  /project/:project_key
  param: { module: project, action: detail }

help:
  url:  /help
  param: { module: other, action: help }

agreement:
  url:  /agreement
  param: { module: other, action: agreement }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*