# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        'incl 2'
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [usertop.css, jquery.easypiechart.css, colorbox.css, style.css]

  javascripts:    [jquery-1.11.0.min.js, jquery.colorbox-min.js, main2.js, jquery.easypiechart.min.js, usertopeng.js, usertop.js ]

  has_layout:     true
  layout:         mainLayout
