dev:
  inclv2:
    param:
      classname: DebugPDO
      debug: { realmemoryusage: true, details: { time: { enabled: true }, slow: { enabled: true, threshold: 0.1 }, mem: { enabled: true }, mempeak: { enabled: true }, memdelta: { enabled: true } } }
test:
  inclv2:
    param:
      classname: DebugPDO
all:
  inclv2:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:dbname=inclv2;host=localhost'
      username: root
      password: root
      encoding: utf8
      persistent: true
      pooling: true
