all:
  incl2:
    class: sfPropelDatabase
    param:
      classname: DebugPDO
      dsn: 'pgsql:host=localhost;dbname=incl2'
      username: incl
      password: incl
      encoding: utf8
      persistent: true
      pooling: true
      debug: { realmemoryusage: true, details: { time: { enabled: true }, slow: { enabled: true, threshold: 0.1 }, mem: { enabled: true }, mempeak: { enabled: true }, memdelta: { enabled: true } } }
dev:
  incl2:
    class: sfPropelDatabase
    param:
      classname: DebugPDO
      dsn: 'pgsql:host=localhost;dbname=incl2'
      username: incl
      password: incl
      encoding: utf8
      persistent: true
      pooling: true
      debug: { realmemoryusage: true, details: { time: { enabled: true }, slow: { enabled: true, threshold: 0.1 }, mem: { enabled: true }, mempeak: { enabled: true }, memdelta: { enabled: true } } }
test:
  incl2:
    class: sfPropelDatabase
    param:
      classname: DebugPDO
      dsn: 'pgsql:host=localhost;dbname=incl2'
      username: incl
      password: incl
      encoding: utf8
      persistent: true
      pooling: true
      debug: { realmemoryusage: true, details: { time: { enabled: true }, slow: { enabled: true, threshold: 0.1 }, mem: { enabled: true }, mempeak: { enabled: true }, memdelta: { enabled: true } } }
